# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "45da92e216191f0903b247d491eba3ae"
name = "tanstack-start-app-staging"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
